NDefines.NAI.DEVELOPMENT_CAP_BASE = 20
--
NDefines.NAI.ESTATE_MAX_WANTED_INFLUENCE = 75
NDefines.NAI.ESTATE_MIN_WANTED_CROWNLAND = 30
--
NDefines.NAI.INCOME_SAVINGS_FRACTION = 0.3
NDefines.NAI.MAX_BUILDING_COST_INCOME_MONTHS = 50
NDefines.NAI.MAX_SAVINGS = 50
NDefines.NAI.EXTRA_SURPLUS_WHEN_NEEDING_BUILDINGS = 0.2
NDefines.NAI.DESIRED_DEFICIT = 0.15
NDefines.NAI.DESIRED_SURPLUS = 0.15
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS = 3
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS_PEACETIME = 24
NDefines.NAI.COLONY_BUDGET_FRACTION = 0.3
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MAX = 0.4
NDefines.NAI.ADVISOR_PROMOTION_AGE_CUTOFF = 45
NDefines.NAI.RECRUIT_ADVISOR_BASE_AI_DESIRE = 75.0
NDefines.NAI.PROMOTE_ADVISOR_BASE_AI_DESIRE = 25.0
NDefines.NAIEconomy.STATE_MAINTENANCE_FRACTION = 0.3
NDefines.NAIEconomy.BUDGETING_ADJUSTMENT_STEP = 0.125
NDefines.NAIEconomy.MILITARY_FOCUS_DEFAULT = 1.3
NDefines.NAIEconomy.MILITARY_FOCUS_LOWER_BOUND = 1
NDefines.NAIEconomy.MILITARY_FOCUS_UPPER_BOUND = 1.6
NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY = 100.0
NDefines.NAI.REPAY_LOAN_BASE_AI_DESIRE = 200.0
NDefines.NAI.DEBASE_THRESHOLD = 1000
--
NDefines.NAI.EDICT_VALUE_THRESHOLD = 20
NDefines.NAI.EDICT_VALUE_THRESHOLD_MULTIPLY_LOW_INCOME = 1.2
NDefines.NAI.UPGRADE_CENTER_OF_TRADE_BASE_AI_DESIRE = 75.0
NDefines.NAI.UPGRADE_CENTER_OF_TRADE_AI_POWER_DESIRE = 10.0
NDefines.NAI.AI_TOTAL_DEV_CULTURE_MULTIPLIER = 10
--
NDefines.NAI.MISSION_PICK_CHANCE = 50
NDefines.NAI.PS_SHORT_TERM_POOL = 150
NDefines.NAI.DEFENDER_OF_FAITH_BASE_AI_DESIRE = 10
--
NDefines.NAI.DIPLOMATIC_ACTION_TAKE_ON_DEBT_ALLY_FACTOR = 50
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_INDEBTED_FACTOR = 50
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_WAR_WITH_RIVAL_FACTOR = 40
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_POWERBALANCE_FACTOR = 50
NDefines.NAI.DIPLOMATIC_ACTION_GIFT_POWERBALANCE_FACTOR_PLAYER = 50
NDefines.NAI.DIPLOMATIC_ACTION_GUARANTEE_POWERBALANCE_FACTOR = 50
NDefines.NAI.DIPLOMATIC_ACTION_WARNING_WARN_FACTOR = 60
--
NDefines.NAIEconomy.ARMY_FRACTION_PEACEFUL = 1.2
NDefines.NAIEconomy.ARMY_FRACTION_MILITARIST = 1.3
NDefines.NAIEconomy.NAVY_FRACTION_PEACEFUL = 1.2
NDefines.NAIEconomy.NAVY_FRACTION_CAPITALIST = 1.2
NDefines.NAIEconomy.FORT_FRACTION_MILITARIZE = 1.5
NDefines.NAIEconomy.FORT_FRACTION_MILITARIST = 1.33
NDefines.NAIEconomy.FORT_FRACTION_CAPITALIST = 1.0
NDefines.NAI.TRANSPORT_FRACTION = 0.35
NDefines.NAI.ARMY_BUDGET_FRACTION = 1
NDefines.NAI.FORT_BUDGET_FRACTION = 0.65
--
NDefines.NAI.PEACE_TERMS_WAR_REPARATIONS_BASE_MULT = 1
--
NDefines.NAI.AGGRESSIVENESS = 250
NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 450
--
NDefines.NAI.DIPLOMATIC_ACTION_INFLUENCE_NATION_ALLY_FACTOR	= 35
NDefines.NAI.DIPLOMATIC_ACTION_PERSONALITY_MULT = 1.65
NDefines.NAI.DIPLOMATIC_ACTION_IMPROVE_RELATIONS_VASSALIZE_FACTOR = 200
NDefines.NAI.DIPLOMATIC_ACTION_IMPROVE_RELATIONS_ALLY_FACTOR = 80
NDefines.NAI.DIPLOMATIC_ACTION_TAKE_ON_DEBT_POWERBALANCE_FACTOR = 30
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_BASE_FACTOR = 80
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_STRATEGY_FACTOR = 1.2
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_OTHER_CB_FACTOR = 1.0
--
NDefines.NCountry.RELEASED_NATION_ARMY_SIZE = 0.75
NDefines.NCountry.STARTING_ARMY_SIZE = 0.85
--
NDefines.NAI.PEACE_DESPERATION_FACTOR = 35
NDefines.NAI.PEACE_REBELS_FACTOR = 30
NDefines.NAI.PEACE_ALLY_REBELS_MULT = 1.25
NDefines.NAI.PEACE_CAPITAL_FACTOR = 20
NDefines.NAI.PEACE_CALL_FOR_PEACE_FACTOR = 20
NDefines.NAI.PEACE_TIME_MAX_MONTHS = 120
NDefines.NAI.PEACE_TIME_MONTHS = 60
NDefines.NAI.PEACE_MILITARY_STRENGTH_FACTOR = 20
--
NDefines.NAI.PEACE_HIGH_WAR_EXHAUSTION_FACTOR = 2
NDefines.NAI.PEACE_HIGH_WAR_EXHAUSTION_THRESHOLD = 8
NDefines.NAI.PEACE_WAR_EXHAUSTION_FACTOR = 1
NDefines.NAI.PEACE_TERMS_BASE_SCORE = 15
NDefines.NAI.PEACE_TERMS_PROVINCE_IMPERIAL_LIBERATION_MULT = 5.0
NDefines.NAI.PEACE_TERMS_PROVINCE_NO_CB_MULT = 1.0
NDefines.NAI.PEACE_TERMS_PROVINCE_CLAIM_MULT = 3.0
NDefines.NAI.PEACE_TERMS_PROVINCE_CORE_MULT = 5.0
NDefines.NAI.PEACE_TERMS_PROVINCE_NO_INTEREST_MULT = 0.1
NDefines.NAI.PEACE_TERMS_PROVINCE_VASSAL_MULT = 1.0
NDefines.NAI.PEACE_TERMS_RELEASE_VASSALS_BASE_MULT = 0.9
NDefines.NAI.PEACE_TERMS_TRANSFER_VASSALS_BASE_MULT = 1.0
NDefines.NAI.PEACE_TERMS_PROVINCE_REAL_ADJACENT_MULT = 1.0
NDefines.NAI.PEACE_TERMS_RETURN_CORES_VASSAL_MULT = 20
NDefines.NAI.PEACE_TERMS_PROVINCE_NOT_ADJACENT_MULT = 0.3
--
NDefines.NAI.ASSIMILATION_INTEREST_AMOUNT_FACTOR = 100
NDefines.NAI.BORDER_DISTANCE_SCORE_IMPACT = 4.0
NDefines.NAI.PURSUE_DISTANCE = 80
--
NDefines.NAI.INVADING_MAX_AWAY_RATIO = 0.75
NDefines.NAI.INVADING_BRAVERY = 1.5
NDefines.NAI.INVASION_ARMY_LOOKUP_INTERVAL_ON_FAILURE = 10
--
NDefines.NAI.REGION_PLANNING_HOMELAND_PRIORIZATION = 6
NDefines.NAI.REGIMENTS_PER_GENERAL = 20
NDefines.NAI.ONLY_INFANTRY_MERCS = 0